msm8998-common: Add missing perf entries in framework compatibility matrix
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.qti.hardware.servicetracker@1.2::IServicetracker/default
    vendor.qti.memory.pasrmanager@1.1::IPasrManager/pasrhal
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 3.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 3 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Change-Id: I751e62de5344ef3d3da5bcd12ab480f1556e5e85