msm8998-common: Add missing gnss entries in framework compatibility matrix
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.gnss@1.0::IGnss/gnss_vendor
    vendor.qti.gnss@1.2::ILocHidlGnss/gnss_vendor
    vendor.qti.gnss@2.1::ILocHidlGnss/gnss_vendor
    vendor.qti.gnss@3.0::ILocHidlGnss/gnss_vendor
    vendor.qti.gnss@4.0::ILocHidlGnss/gnss_vendor
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 3.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 3 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Change-Id: Ib3fca95395864f700d35855b5ee6285ff44809f9