msm8998-common: Add missing qti wifi entries in framework compatibility matrix
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.qti.hardware.wifi.wificfr@1.0::IWificfr/wificfr
    vendor.qti.hardware.wifi.wifimyftm@1.0::IWifiMyFtm/default
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 3.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 3 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.

Change-Id: Ia26bee0a9c63416c37c4b3eccc8f79c4246fea06